const CONSTANTS = {
  TOGGLE_CART_HIDDEN: 'TOGGLE_CART_HIDDEN',
  ADD_ITEMTO_CART: 'ADD_ITEMTO_CART',
  CLEAR_ITEM_FROM_CART: 'CLEAR_ITEM_FROM_CART',
  REMOVE_ITEM: 'REMOVE_ITEM',
};
export default CONSTANTS;
